import type { NextPage } from 'next'
import Head from 'next/head'
import BasePage from '../components/base-page'
import { useUser } from '../hooks/use-user'

import { signIn, signOut } from '../lib/supabase'

const Home: NextPage = () => {
  const user = useUser()

  return (
    <BasePage>
      <Head>
        <title>Shapely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto py-12 text-center">
        {user ? (
          <div>
            <p>Welcome {user.user_metadata.name}!</p>
            <button className="btn" onClick={signOut}>
              Sign out
            </button>
          </div>
        ) : (
          <button className="btn" onClick={signIn}>
            Sign in with Google
          </button>
        )}
      </div>
    </BasePage>
  )
}

export default Home
