import type { NextPage } from "next"
import Head from "next/head"

import { signIn } from "../lib/supabase"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shapely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={signIn}>Sign in with Google</button>
    </div>
  )
}

export default Home
