import type { NextPage } from 'next'
import Head from 'next/head'
import BasePage from '../components/base-page'
import { useUser } from '../hooks/use-user'

import { signIn, signOut } from '../lib/supabase'

const Home: NextPage = () => {
  const user = useUser()

  return (
    <BasePage>
      <Head>
        <title>Shapely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? (
        <div>
          <p>Welcome {user.user_metadata.name}!</p>
          <button onClick={signOut} className="p-4 m-4 text-lg bg-red-200">
            Sign out
          </button>
        </div>
      ) : (
        <button onClick={signIn} className="p-4 m-4 text-lg bg-red-200">
          Sign in with Google
        </button>
      )}
    </BasePage>
  )
}

export default Home
