import type { NextPage } from "next"
import Head from "next/head"
import { useUser } from "../hooks/use-user"

const NextDate: NextPage = () => {
  const user = useUser()

  return (
    <div>
      <Head>
        <title>Shapely</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hello World {user.user_metadata.name}!</div>
      <div>TODOs: this page is for letting users confirm their next video chat</div>
    </div>
  )
}

export default NextDate
